### ISSUE TITLE
Do not specify both @height and @width on img elements

### ISSUE THREAD

**Issue by cmsmcq** [ADHO/dhconvalidator#66]
The HTML generated by dhconvalidator currently includes img elements of the form `<img src=“Pictures/foo.jpg" alt="" class="graphic" width="100%" height="100%”/>`. 

This causes vertical stretching (and possibly vertical compression in some cases), as the browser seeks to force the image into a height/width ratio which matches the ratio of the current container width (the column width, in the output I've seen) to whatever the browser thinks `height="100%"` means.  (Safari, at least, takes it to mean the current display-window height.)  On some images, the distortion is not very noticeable; on others it is very noticeable and unacceptable.

In my experience I get much better results specifying width only, because then the height of the image defaults to whatever is necessary to give the image its native height/width ratio.  I believe this is what dhconvalidator should do:  img elements should take the form `<img src=“Pictures/foo.jpg" alt="" class="graphic" width="100%" />` instead of that shown above.

Actually, I believe that it is currently held to be better practice not to use the `width` and `height` attributes at all, but to use CSS, in a `style` attribute if necessary.   So I think some Web experts would recommend the form  `<img src=“Pictures/foo.jpg" alt="" class="graphic" style="width: 100%;" />` instead.  That would work for me, too.

If I can manage to do so, I will attach a screen shot showing a browser displaying the HTML in a DHC file I generated half an hour ago, showing the vertical distortion of an image, and a second screen shot showing the same browser displaying a version of the HTML in which the `height="100%"` attributes have been deleted.

![screen shot 2018-04-27 at 1 26 03 pm](https://user-images.githubusercontent.com/4857689/39381366-1a29a582-4a1f-11e8-91b9-4759381dcf3a.png)
![screen shot 2018-04-27 at 1 25 54 pm](https://user-images.githubusercontent.com/4857689/39381383-2ac1a444-4a1f-11e8-9e9e-b580aa999c99.png)

The images don't seem to be displaying here, but the distorted display can be seen at http://mlcd.blackmesatech.com/mlcd/2018/Talks/MexicoDF-201806/images/dhconvalidator.image.2.png
and the corrected display at http://mlcd.blackmesatech.com/mlcd/2018/Talks/MexicoDF-201806/images/dhconvalidator.image.1.png

**Comment by christofs** [comment]
Thank you for this feedback. The way you not only identify a problem but also propose a solution is very much appreciated. We'll look into it.

**Comment by aramiscd** [comment]
Fixed in https://github.com/ADHO/dhconvalidator/pull/68.  Again, thanks for your valuable feedback.

**Comment by dodinh** [comment]
I had an inquiry from a user who had smaller images than available space. Such images are unnecessarily enlarged with the current approach.

A cleaner solution, IMHO, would be to use the "graphic" CSS class which is already used for `<img>` tags; i.e., adding a class "graphic" to `src/main/webapp/VAADIN/themes/dhconvalidator/styles.css` and setting `max-width` to 100%.
