### ISSUE TITLE
Error when using the using convalidator on https://adho.org/dhconvalidator-2019/popup/DHConvalidatorServices

### ISSUE THREAD

**Issue by tobiasschweizer** [ADHO/dhconvalidator#74]
I get an error when converting a Word file to XML on https://adho.org/dhconvalidator-2019/popup/DHConvalidatorServices. Who can I ask for support?

**Comment by mpetris** [comment]
Usually the local organizers of the conference know who can help as the DHConvalidator setup and support is per conference. In this case [dh2019.org](https://dh2019.adho.org/) provides an info address for support.

**Comment by aramiscd** [comment]
Can you provide an example file?  And a bit more context maybe?  Did you use the docx template provided by the DHConvalidator?  Im asking because the DHConvalidator can't convert any docx file to xml.  It has to be based on the provided template.
